/***************************************************/
/* dffapi 2.0
/* https://github.com/DK22Pac/dffapi
/*
/* RGBA Color (0-255)
/*
/***************************************************/
#pragma once
#include "gtaTypes.h"

struct gtaColor {
    gtaUChar r = 255;
    gtaUChar g = 255;
    gtaUChar b = 255;
    gtaUChar a = 255;

    gtaColor();
    gtaColor(gtaUChar red, gtaUChar green, gtaUChar blue, gtaUChar alpha = 255);
    void set(gtaUChar red, gtaUChar green, gtaUChar blue, gtaUChar alpha = 255);
    void set(gtaColor const &color);
    gtaUChar &operator[](gtaUInt index);
    gtaUChar operator[](gtaUInt index) const;
    gtaString toString() const;
    gtaBool compareRGB(gtaColor const &color);
};

gtaBool operator==(gtaColor const &a, gtaColor const &b);
gtaBool operator!=(gtaColor const &a, gtaColor const &b);

extern const gtaColor gtaLightCoral;
extern const gtaColor gtaSalmon;
extern const gtaColor gtaDarkSalmon;
extern const gtaColor gtaCrimson;
extern const gtaColor gtaRed;
extern const gtaColor gtaFireBrick;
extern const gtaColor gtaDarkRed;
extern const gtaColor gtaPink;
extern const gtaColor gtaLightPink;
extern const gtaColor gtaHotPink;
extern const gtaColor gtaDeepPink;
extern const gtaColor gtaMediumVioletRed;
extern const gtaColor gtaPaleVioletRed;
extern const gtaColor gtaLightSalmon;
extern const gtaColor gtaCoral;
extern const gtaColor gtaTomato;
extern const gtaColor gtaOrangeRed;
extern const gtaColor gtaDarkOrange;
extern const gtaColor gtaOrange;
extern const gtaColor gtaGold;
extern const gtaColor gtaYellow;
extern const gtaColor gtaLightYellow;
extern const gtaColor gtaLemonChion;
extern const gtaColor gtaLightGoldenrodYellow;
extern const gtaColor gtaPapayaWhip;
extern const gtaColor gtaMoccasin;
extern const gtaColor gtaPeachPu;
extern const gtaColor gtaPaleGoldenrod;
extern const gtaColor gtaKhaki;
extern const gtaColor gtaDarkKhaki;
extern const gtaColor gtaLavender;
extern const gtaColor gtaThistle;
extern const gtaColor gtaPlum;
extern const gtaColor gtaViolet;
extern const gtaColor gtaOrchid;
extern const gtaColor gtaFuchsia;
extern const gtaColor gtaMagenta;
extern const gtaColor gtaMediumOrchid;
extern const gtaColor gtaMediumPurple;
extern const gtaColor gtaBlueViolet;
extern const gtaColor gtaDarkViolet;
extern const gtaColor gtaDarkOrchid;
extern const gtaColor gtaDarkMagenta;
extern const gtaColor gtaPurple;
extern const gtaColor gtaIndigo;
extern const gtaColor gtaSlateBlue;
extern const gtaColor gtaDarkSlateBlue;
extern const gtaColor gtaGreenYellow;
extern const gtaColor gtaChartreuse;
extern const gtaColor gtaLawnGreen;
extern const gtaColor gtaLime;
extern const gtaColor gtaLimeGreen;
extern const gtaColor gtaPaleGreen;
extern const gtaColor gtaLightGreen;
extern const gtaColor gtaMediumSpringGreen;
extern const gtaColor gtaSpringGreen;
extern const gtaColor gtaMediumSeaGreen;
extern const gtaColor gtaSeaGreen;
extern const gtaColor gtaForestGreen;
extern const gtaColor gtaGreen;
extern const gtaColor gtaDarkGreen;
extern const gtaColor gtaYellowGreen;
extern const gtaColor gtaOliveDrab;
extern const gtaColor gtaOlive;
extern const gtaColor gtaDarkOliveGreen;
extern const gtaColor gtaMediumAquamarine;
extern const gtaColor gtaDarkSeaGreen;
extern const gtaColor gtaLightSeaGreen;
extern const gtaColor gtaDarkCyan;
extern const gtaColor gtaTeal;
extern const gtaColor gtaAqua;
extern const gtaColor gtaCyan;
extern const gtaColor gtaLightCyan;
extern const gtaColor gtaPaleTurquoise;
extern const gtaColor gtaAquamarine;
extern const gtaColor gtaTurquoise;
extern const gtaColor gtaMediumTurquoise;
extern const gtaColor gtaDarkTurquoise;
extern const gtaColor gtaCadetBlue;
extern const gtaColor gtaSteelBlue;
extern const gtaColor gtaLightSteelBlue;
extern const gtaColor gtaPowderBlue;
extern const gtaColor gtaLightBlue;
extern const gtaColor gtaSkyBlue;
extern const gtaColor gtaLightSkyBlue;
extern const gtaColor gtaDeepSkyBlue;
extern const gtaColor gtaDodgerBlue;
extern const gtaColor gtaCornlowerBlue;
extern const gtaColor gtaMediumSlateBlue;
extern const gtaColor gtaRoyalBlue;
extern const gtaColor gtaBlue;
extern const gtaColor gtaMediumBlue;
extern const gtaColor gtaDarkBlue;
extern const gtaColor gtaNavy;
extern const gtaColor gtaMidnightBlue;
extern const gtaColor gtaCornsilk;
extern const gtaColor gtaBlanchedAlmond;
extern const gtaColor gtaBisque;
extern const gtaColor gtaNavajoWhite;
extern const gtaColor gtaWheat;
extern const gtaColor gtaBurlyWood;
extern const gtaColor gtaTan;
extern const gtaColor gtaRosyBrown;
extern const gtaColor gtaSandyBrown;
extern const gtaColor gtaGoldenrod;
extern const gtaColor gtaDarkGoldenrod;
extern const gtaColor gtaPeru;
extern const gtaColor gtaChocolate;
extern const gtaColor gtaSaddleBrown;
extern const gtaColor gtaSienna;
extern const gtaColor gtaBrown;
extern const gtaColor gtaMaroon;
extern const gtaColor gtaWhite;
extern const gtaColor gtaSnow;
extern const gtaColor gtaHoneydew;
extern const gtaColor gtaMintCream;
extern const gtaColor gtaAzure;
extern const gtaColor gtaAliceBlue;
extern const gtaColor gtaGhostWhite;
extern const gtaColor gtaWhiteSmoke;
extern const gtaColor gtaSeashell;
extern const gtaColor gtaBeige;
extern const gtaColor gtaOldLace;
extern const gtaColor gtaFloralWhite;
extern const gtaColor gtaIvory;
extern const gtaColor gtaAntiqueWhite;
extern const gtaColor gtaLinen;
extern const gtaColor gtaLavenderBlush;
extern const gtaColor gtaMistyRose;
extern const gtaColor gtaGainsboro;
extern const gtaColor gtaLightGrey;
extern const gtaColor gtaSilver;
extern const gtaColor gtaDarkGray;
extern const gtaColor gtaGray;
extern const gtaColor gtaDimGray;
extern const gtaColor gtaLightSlateGray;
extern const gtaColor gtaSlateGray;
extern const gtaColor gtaDarkSlateGray;
extern const gtaColor gtaBlack;
extern const gtaColor gtaTransparent;
